import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SideBar from "@/components/SideBar";
import MenuIcon from "@mui/icons-material/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex items-start justify-between max-w-screen min-h-screen max-h-fit font-poppins  bg-bgClr">
          <SideBar />
          <div className="w-full min-h-screen flex flex-col ">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
